<?php

/**
 * atlanticalloys
 *
 * WARNING: This file is part of the atlanticalloys theme. DO NOT edit this file
 * under any circumstances, as the changes will be lost in the case of a theme update.
 * Please do all modifications in the form of a child theme.
 *
 * @since   1.0.0
 * @package WL
 * @author  Nucleus
 * @license GPL-2.0+
 * @link    http://nucleus.eti.br/
 */

namespace WL\Theme;

/**
 * Theme post types.
 *
 * @since  1.0.0
 */
class Taxonomy {

	public function __construct() {
		add_action( 'init', array( $this, 'register_taxonomies' ) );
	}

	public function register_taxonomies() {
		// CPT Products
		$this->register(
			'products-category',
			'Categorias',
			'Categoria',
			'products'
		);
	}

	private function register( $name_slug, $name_plural, $name_singular, $name_cpt ) {
		register_taxonomy(
			$name_slug,
			$name_cpt,
			array(
				'labels'            => array(
					'name'                       => _x( $name_plural, 'Taxonomy General Name', 'atlanticalloys' ),
					'singular_name'              => _x( $name_singular, 'Taxonomy Singular Name', 'atlanticalloys' ),
					'menu_name'                  => __( $name_plural, 'atlanticalloys' ),
					'all_items'                  => __( 'Todos os ' . $name_plural, 'atlanticalloys' ),
					'parent_item'                => __( $name_singular . ' Pai', 'atlanticalloys' ),
					'parent_item_colon'          => __( $name_singular . ' pai (dois pontos)', 'atlanticalloys' ),
					'new_item_name'              => __( 'Nome do novo ' . $name_singular, 'atlanticalloys' ),
					'add_new_item'               => __( 'Adicionar novo ' . $name_singular, 'atlanticalloys' ),
					'edit_item'                  => __( 'Editar ' . $name_singular, 'atlanticalloys' ),
					'update_item'                => __( 'Atualizar ' . $name_singular, 'atlanticalloys' ),
					'view_item'                  => __( 'Ver ' . $name_singular, 'atlanticalloys' ),
					'separate_items_with_commas' => __( 'Separe ' . $name_plural . ' com vírgulas', 'atlanticalloys' ),
					'add_or_remove_items'        => __( 'Adicionar ou remover ' . $name_singular, 'atlanticalloys' ),
					'choose_from_most_used'      => __( 'Escolha entre os ' . $name_plural . ' mais usados', 'atlanticalloys' ),
					'popular_items'              => __( $name_singular . ' popular', 'atlanticalloys' ),
					'search_items'               => __( 'Buscar ' . $name_singular, 'atlanticalloys' ),
					'not_found'                  => __( $name_singular . ' não encontrado', 'atlanticalloys' ),
					'no_terms'                   => __( 'Sem ' . $name_singular, 'atlanticalloys' ),
					'items_list'                 => __( 'Lista de ' . $name_plural, 'atlanticalloys' ),
					'items_list_navigation'      => __( 'Navegação na lista de ' . $name_plural, 'atlanticalloys' ),
				),
				'hierarchical'      => true,
				'public'            => true,
				'show_ui'           => true,
				'show_admin_column' => true,
				'show_in_nav_menus' => true,
				'show_tagcloud'     => true,
				'query_var'         => false,
				'show_in_rest'      => true,
				'supports'          => array(
					'title',
					'thumbnail',
				),
			)
		);
	}
}
